language:
    go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - release
    - tip

matrix:
    allow_failures:
        - go: release
        - go: tip
    fast_finish: true

script:
    - go test -v ./...
